name: Test suite

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux-x64:
    runs-on: ubuntu-22.04
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y -f \
        build-essential \
        g++ \
        pkg-config

    - name: Build
      run: |
        ./scripts/bz.py
        chmod +x ./bin/pocket-http-linux_x64
        
    - name: List bin directory contents
      run: ls -la ./bin/
      
    - name: Run Binary
      run: ./bin/pocket-http-linux_x64 GET "https://www.example.com"

  build-linux-arm64:
    runs-on: ubuntu-22.04-arm
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y -f \
        build-essential \
        g++ \
        pkg-config

    - name: Build
      run: |
        ./scripts/bz.py
        chmod +x ./bin/pocket-http-linux_arm64
        
    - name: List bin directory contents
      run: ls -la ./bin/
      
    - name: Run Binary
      run: ./bin/pocket-http-linux_arm64 GET "https://www.example.com"


  build-windows:
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: python ./scripts/bz.py
      shell: cmd
      
    - name: List bin directory contents
      run: dir bin
      shell: cmd
      
    - name: Run Binary
      run: .\bin\pocket-http-win_x64.exe GET "https://www.example.com"
      shell: cmd

  build-darwin:
    runs-on: macos-14
    strategy:
      matrix:
        arch: [x64, arm64]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        ./scripts/bz.py --target_arch ${{ matrix.arch }}
        chmod +x ./bin/pocket-http-mac_${{ matrix.arch }}
        
    - name: List bin directory contents
      run: ls -la ./bin/
        
    - name: Run Binary
      run: ./bin/pocket-http-mac_${{ matrix.arch }} GET "https://www.example.com"