name: Test macOS Build

on:
  workflow_dispatch:

jobs:
  amalgamate:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Make amalgamate script executable
      run: chmod +x ./scripts/amalgamate.py

    - name: Amalgamate
      run: ./scripts/amalgamate.py

    - name: Upload amalgamated files
      uses: actions/upload-artifact@v4
      with:
        name: amalgamated-files
        path: dist

  build-darwin:
    needs: amalgamate
    runs-on: macos-14
    strategy:
      fail-fast: true
      matrix:
        arch: [x64, arm64]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: List SystemRoot Certificates
      run: security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain | grep "BEGIN CERTIFICATE" | wc -l
    
    - name: List System Keychain Certificates
      run: security find-certificate -a -p /Library/Keychains/System.keychain | grep "BEGIN CERTIFICATE" | wc -l

    - name: List Login Keychain Certificates
      run: |
        if [ -f ~/Library/Keychains/login.keychain-db ]; then
          security find-certificate -a -p ~/Library/Keychains/login.keychain-db | grep "BEGIN CERTIFICATE" | wc -l
        else
          echo "0 (Login keychain not found)"
        fi

    - name: Download amalgamated files
      uses: actions/download-artifact@v4
      with:
        name: amalgamated-files
        path: dist
    
    - name: Delete Non Amalgamated Files
      run: |
        rm -f ./src/*.cpp
        rm -rf ./src/Sockets
        rm -rf ./include/pockethttp

    - name: Install build dependencies
      run: |
        # Ensure we have the necessary build tools
        xcode-select --install || true

    - name: Make build script executable
      run: chmod +x ./scripts/bz.py

    - name: Build
      run: ./scripts/bz.py --target_arch ${{ matrix.arch }}  --verbose

    - name: Make binary executable
      run: chmod +x ./bin/pocket-http_mac_${{ matrix.arch }}
        
    - name: List bin directory contents
      run: ls -la ./bin/
      
    - name: Verify binary exists
      run: |
        if [ ! -f "./bin/pocket-http_mac_${{ matrix.arch }}" ]; then
          echo "Binary not found!"
          exit 1
        fi
        
    - name: Run Binary
      run: ./bin/pocket-http_mac_${{ matrix.arch }} "https://www.example.com"